language: objective-c
osx_image: xcode8.1

before_install:
  - gem install slather --no-ri --no-rdoc
script:
  - xcodebuild clean test -project ./SwiftWorkshop5.xcodeproj -scheme swiftProtocolsAndGenerics -destination 'platform=iOS Simulator,name=iPhone 7' TEST_AFTER_BUILD=YES -configuration Debug -enableCodeCoverage=YES
  - slather
